# Generated by Django 3.2.9 on 2021-11-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('cycle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cycle_name', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('deskripsi', models.TextField(default='')),
                ('harga', models.IntegerField(default=0)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
            ],
        ),
    ]
